### Llamada a Google
GET https://google.com

### Inciso 1
GET https://jsonplaceholder.typicode.com/users

### Inciso 2
GET https://jsonplaceholder.typicode.com/users/10

### Inciso 3
GET https://jsonplaceholder.typicode.com/users/100

### Inciso 4
POST https://jsonplaceholder.typicode.com/users
Content-Type: application/json; charset=utf-8

{
    "name": "test test",
    "username": "iteso",
    "email": "asdf@its.com"
}

###
GET http://127.0.0.1:3000


