"use strict";

class HabitException{
	constructor(errorMessage){
		this.errorMessage = errorMessage;
	}
}

class Habit{
	constructor(title) {
        this._id = generateId('habit');
        this.title = title
        this.dificultad = "easy"
        this.tagId = ''
        this.reset = "semanal"
        this.bntCnt = ["positive","negative"]
        this.status = "weak"
        this.streak = 0
    }
    //id
    get id() {
        return this._id;
    }
    set id(val) {
    	throw new HabitException('id have to be autogenerated.');
    }
    //title
    get title() {
        return this._title;
    }
    set title(val) {
    	if(typeof val !== "string" || val == ''){
    		throw new HabitException('Habit title cannot be empty.');
    	}
        this._title = val;
    }
    //dificultad
    get dificultad() {
        return this._dificultad;
    }
    set dificultad(val) {
    	if(typeof val !== "string" || val == ''){
    		throw new HabitException('dificultad cannot be empty.');
    	}
        this._dificultad = val;
    }
    //tagId
    get tagId() {
        return this._tagId;
    }
    set tagId(val) {
    	if(typeof val !== "string"){
    		throw new HabitException('tagId is not valid.');
    	}
        this._tagId = val;
    }
    //reset
    get reset() {
        return this._reset;
    }
    set reset(val) {
    	if(typeof val !== "string" || val == ''){
    		throw new HabitException('reset cannot be empty.');
    	}
        this._reset = val;
    }
    //bntCnt
    get bntCnt() {
        return this._bntCnt;
    }
    set bntCnt(val) {
        this._bntCnt = [];
        if(Array.isArray(val)){
            for(let bnt of val){
                if(bnt !== "positive" || bnt !== "negative" || bnt !== ''){
                    throw new HabitException('bntCnt not valid.');
                }
                this._bntCnt.push(bnt);
            }
        } else {
            if(val !== "positive" || val !== "negative" || val !== ''){
                throw new HabitException('bntCnt not valid.');
            }
            this._bntCnt.push(val);
        }
    }
    //status
    get status() {
        return this._status;
    }
    set status(val) {
        if(val !== "weak" || val !== "strong"){
            throw new HabitException('status not valid.');
        }
        if(typeof val !== "string" || val == ''){
            throw new HabitException('status cannot be empty.');
        }
        this._status = val;
    }
    //streak
    get streak() {
        return this._streak;
    }
    set streak(val) {
        if(typeof val !== "number" || val < 0){
            throw new HabitException('streak cannot be negative or not number.');
        }
        this._streak = val;
    }

    //Convertimos el String de JSON recibido 
    //en una nueva instancia de Habito
    static createFromJson(jsonValue){
    	let obj = JSON.parse(jsonValue);
    	return Habit.createFromObject(obj);
    }

    //Convertimos el objeto recibido en una
    //nueva instancia de Habito

    //le entra algo como let a = {'bntCnt': 15};
    static createFromObject(obj){
    	let newHabit = {};
    	Object.assign(newHabit, obj); //clone object and handle
    	Habit.cleanObject(newHabit);
    	//Falta ir pasando los valores a un Habito que pertenezca a la clase
    	let habit = new Habit(newHabit['title']);
    	return habit;
    }

    //Limpiamos el objeto recibido de todos
    //aquellos valores ajenos a la clase Habit
    static cleanObject(obj){
    	const HabitProperties = ['title', 'dificultad', 'tagId', 'reset', 'bntCnt', 'status', 'streak'];
        
        for (let prop in obj){
    		//if prop not in HabitProperties
    		if(HabitProperties.indexOf(prop) == -1){
            	delete obj[prop];
            }
    	}
    }


}
