"use strict";

class userDataException{
	constructor(errorMessage){
		this.errorMessage = errorMessage;
	}
}

class TagProxy{
    constructor(tagId){
        this.tagId = tagId;
    }
}

class userData{
	constructor(avatarImg, avatarName, avatarLevel, avatarCoins, avatarHealth, avatarExp){
        this._id = generateId('user'); //al iniciar mando {nombre, correo, contraseña, level, coins, health}
        this.avatarImg = avatarImg //guarda num
        this.avatarName = avatarName
        this.avatarLevel = avatarLevel //default 1
        this.avatarCoins = avatarCoins //default 1000
        this.avatarHealth = avatarHealth //default 1000
        this.avatarExp = avatarExp //default 0
	}
    //id
    get id() {
        return this._id;
    }
    set id(val) {
        throw new userDataException('id have to be autogenerated.');
    }
    //avatarImg
    get avatarImg() {
        return this._avatarImg;
    }
    set avatarImg(val) {
        if(typeof val !== "string" || val == ''){
            throw new userDataException('Daily avatarImg cannot be empty.');
        }
        this._avatarImg = val;
    }
    //avatarName
    get avatarName() {
        return this._avatarName;
    }
    set avatarName(val) {
        if(typeof val !== "string" || val == ''){
            throw new userDataException('Daily avatarName cannot be empty.');
        }
        this._avatarName = val;
    }
    //avatarLevel
    get avatarLevel() {
        return this._avatarLevel;
    }
    set avatarLevel(val) {
        if(typeof val !== "number" || val < 0){
            throw new userDataException('avatarLevel cannot be negative or not number.');
        }
        this._avatarLevel = val;
    }
    //avatarCoins
    get avatarCoins() {
        return this._avatarCoins;
    }
    set avatarCoins(val) {
        if(typeof val !== "number" || val < 0){
            throw new userDataException('avatarCoins cannot be negative or not number.');
        }
        this._avatarCoins = val;
    }
    //avatarHealth
    get avatarHealth() {
        return this._avatarHealth;
    }
    set avatarHealth(val) {
        if(typeof val !== "number" || val < 0){
            throw new userDataException('avatarHealth cannot be negative or not number.');
        }
        this._avatarHealth = val;
    }
    //avatarExp
    get avatarExp() {
        return this._avatarExp;
    }
    set avatarExp(val) {
        if(typeof val !== "number" || val < 0){
            throw new userDataException('avatarExp cannot be negative or not number.');
        }
        this._avatarExp = val;
    }

    //tagProxies
    get tagProxies() {
        return this._tagProxies;
    }
    set tagProxies(val) {
        throw new userDataException('Proxies can not be set manually.');
    }
    
    //Convertimos el String de JSON recibido 
    //en una nueva instancia de User
    static createFromJson(jsonValue){
        let obj = JSON.parse(jsonValue);
        return User.createFromObject(obj);
    }

    //Convertimos el objeto recibido en una
    //nueva instancia de User

    //le entra algo como let a = {'bntCnt': 15};
    static createFromObject(obj){
        let newUser = {};
        Object.assign(newUser, obj); //clone object and handle
        User.cleanObject(newUser);
        //Falta ir pasando los valores a un User que pertenezca a la clase
        let user = new User(newUser['avatarImg'], newUser['avatarName'], 
                            newUser['avatarLevel'], newUser['avatarCoins'],
                            newUser['avatarHealth'], newUser['avatarExp']);
        return user;
    }

    //Limpiamos el objeto recibido de todos
    //aquellos valores ajenos a la clase User
    static cleanObject(obj){
        const UserProperties = ['avatarImg', 'avatarName', 'avatarLevel', 'avatarCoins', 'avatarHealth', 'avatarExp'];
        
        for (let prop in obj){
            //if prop not in UserProperties
            if(UserProperties.indexOf(prop) == -1){
                delete obj[prop];
            }
        }
    }

        

}
